logging:
  level: INFO
  loggers:
    org.kulov: DEBUG
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
  password: root
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:mysql://localhost:3306/customer

consumer:
  bootstrapServers:
    - 127.0.0.1:9092
  consumerGroupId: test
  keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
  valueDeserializer: com.kulov.bank.CustomerDeserializer



topics:
  - quickstart-events
  - another-topic